name: app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  universal_io: ^2.0.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/categories.json
    - assets/data/ingredients.json
    - assets/data/recipes.json
    - assets/data/tags.json
    - assets/image/

